# Vectors and Matrices in Numpy - Lab

## Introduction

In this lab, you'll solve some simple matrix creation and manipulation exercises based on what you've learned so far in this section. The key takeaway here is to be able to understand how to use indexing with matrices and vectors while applying some basic operations.

## Objectives
You will be able to:
* Define vectors and matrices in NumPy
* Check the shape of vectors and matrices
* Access and manipulate individual scalar components of a matrix. 

## 1. Define two arrays $A$  with shape $ (4 \times 2)$ and $B$ with shape $(2 \times 3)$ 
So    $A =    
  \left[ {\begin{array}{cc}
   1402 & 191 \\
   1371 &  821\\
   949 &  1437 \\
   147 & 1448 \\
  \end{array} }\right]
$
and
$
B =    
  \left[ {\begin{array}{ccc}
   1 & 2 & 3 \\
   4 & 5 & 6\\
  \end{array} }\right]
$

In [1]:
import numpy as np

In [2]:
# Code Here
A = np.mat([[1402,  191],
[1371,  821],
[ 949, 1437],
[ 147, 1448]])

A

matrix([[1402,  191],
        [1371,  821],
        [ 949, 1437],
        [ 147, 1448]])

In [3]:
B = np.mat([[1,2,3],[4,5,6]])

In [4]:
B.shape

(2, 3)

In [6]:
A.shape

(4, 2)

## 3. Print some of the elements from $A$: 
* first row and first column
* first row and second column
* third row and second column
* fourth row and first column

In [13]:
A

matrix([[1402,  191],
        [1371,  821],
        [ 949, 1437],
        [ 147, 1448]])

In [14]:
A[0,0]

1402

In [17]:
A[:,1]

matrix([[ 191],
        [ 821],
        [1437],
        [1448]])

## 4. Write a routine to populate a matrix with random data
* Create an $(3 \times 3)$ Numpy array with all zeros (use `np.zeros()`)
* Access each location $(i,j)$ of this matrix and fill in random values between the range 1 and 10. 

In [7]:
Z = np.mat(np.zeros([3,3]))
Z

matrix([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [8]:
Z = np.mat(np.random.randint(1,10,[3,3]))
Z

matrix([[6, 9, 6],
        [2, 4, 4],
        [7, 1, 4]])

In [9]:
# Code Here (due to random data , your output might be different)

## 5. Turn the above routine into a function
* Create two $(4 \times 4)$ zero valued matrices and fill with random data using the function
* Add the matrices together in numpy 
* Show the results

In [20]:
np.zeros([4,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
def create_random_matrix(dimension_1, dimension_2):
    matrix = np.mat(np.zeros([dimension_1, dimension_2]))
    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            matrix[i,j] = np.random.randint(-100,100)
    return matrix

m1 = create_random_matrix(4,4)
m2 = create_random_matrix(4,4)
print(m1)
print(' ')
print(m2)

[[ 17.  -3. -91. -70.]
 [-92. -61.  87.  -4.]
 [-26. -34. -30.  47.]
 [-39.  53. -88. -59.]]
 
[[-38.  59. -72.  -7.]
 [-62. -80. -40.  -3.]
 [ 36.  62.  89. -58.]
 [ -7.  81.  88. -10.]]


In [21]:
print(m1+m2)

[[ -21.   56. -163.  -77.]
 [-154. -141.   47.   -7.]
 [  10.   28.   59.  -11.]
 [ -46.  134.    0.  -69.]]


## Summary 

In this lab, we saw how to create and manipulate vectors and matrices in numpy. We shall now move forward to learning more complex operations including dot products and inverses. 